laravel/app/Http/routes.php
<?php

Route::group(['middleware' => ['web']], function () {    
    Route::get('/', 'HomeController@index')->name('home');
    Route::post('aceite-de-cookies', 'HomeController@postCookies')->name('aceite-de-cookies.post');
    Route::post('login', 'CadastroAuth\AuthController@login')->name('login-cadastro');
    Route::get('login', 'CadastroAuth\AuthController@showLoginForm')->name('login-cadastro');
    Route::get('logout', 'CadastroAuth\AuthController@logout')->name('logout-cadastro');
    Route::post('criar-senha', 'CadastroAuth\AuthController@createPassword')->name('criar-senha');

    Route::get('esqueci-minha-senha', 'HomeController@esqueci')->name('cadastros.esqueci');
    Route::get('redefinicao-de-senha/{token}', 'CadastroAuth\PasswordController@showResetForm')->name('password-reset');
    Route::post('redefinicao-de-senha', 'CadastroAuth\PasswordController@sendResetLinkEmail')->name('cadastros.redefinicao');
    Route::post('redefinir-senha', 'CadastroAuth\PasswordController@reset')->name('cadastros.redefinir');

    Route::group([
        'middleware'    => ['auth.cadastros']
    ],function (){
        Route::get('cadastrar-notas', 'CadastrarNotaController@cadastrarNota')->name('cadastrar-notas');
        Route::get('extrato-de-bonus', 'ExtratoBonusController@index')->name('extrato-de-bonus');        

        Route::get('cadastrar-revenda', 'CadastrarNotaController@cadastrarRevenda')->name('cadastrar-revenda');
        Route::post('revenda', 'CadastrarNotaController@revenda')->name('revenda');
        Route::get('cadastrar-linha-nova', 'CadastrarNotaController@cadastrarLinhaNova')->name('cadastrar-linha-nova');
        Route::post('linha-nova', 'CadastrarNotaController@linhaNova')->name('linha-nova');

        Route::get('notas-cadastradas', 'CadastrarNotaController@index')->name('notas-cadastradas');
        Route::get('politica-de-privacidade', 'HomeController@politicaDePrivacidade')->name('politica-de-privacidade');
    });

    // Painel
    Route::group([
        'prefix'     => 'painel',
        'namespace'  => 'Painel',
        'middleware' => ['auth']
    ], function() {
        Route::get('/', 'PainelController@index')->name('painel');

        Route::group(['middleware' => 'admin'], function() {
            /* GENERATED ROUTES */

            Route::resource('cadastros', 'CadastrosController');
            Route::resource('notas', 'NotasController');
            Route::resource('bonus', 'BonusController');
            Route::post('pesquisa-notas', 'FiltroPesquisaController@notas')->name('filtro-notas');
            Route::post('pesquisa-bonus', 'FiltroPesquisaController@bonus')->name('filtro-bonus');
            Route::get('reenviar-email-usuario/{id}', 'CadastrosController@reenviaEmailUsuario')->name('email-usuario');
            Route::get('atualiza-saldo/{id}', 'FiltroPesquisaController@atualizaSaldoBonus')->name('atualiza-saldo');
            
            Route::resource('configuracoes', 'ConfiguracoesController', ['only' => ['index', 'update']]);
            Route::resource('usuarios', 'UsuariosController');
            Route::resource('politica-de-privacidade', 'PoliticaDePrivacidadeController', ['only' => ['index', 'update']]);
            Route::get('aceite-de-cookies', 'AceiteDeCookiesController@index')->name('painel.aceite-de-cookies');

            Route::post('ckeditor-upload', 'PainelController@imageUpload');
            Route::post('order', 'PainelController@order');
            Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');

            Route::get('generator', 'GeneratorController@index')->name('generator.index');
            Route::post('generator', 'GeneratorController@submit')->name('generator.submit');
        });
    });

    // Auth
    Route::group([
        'prefix'    => 'painel',
        'namespace' => 'Auth'
    ], function() {
        Route::get('login', 'AuthController@showLoginForm')->name('auth');
        Route::post('login', 'AuthController@login')->name('login');
        Route::get('logout', 'AuthController@logout')->name('logout');
    });
});

laravel/app/Http/Controllers/Painel/AceiteDeCookiesController.php
<?php

namespace App\Http\Controllers\Painel;

use App\Http\Controllers\Controller;
use App\Models\AceiteDeCookies;

class AceiteDeCookiesController extends Controller
{
    public function index()
    {
        $registros = AceiteDeCookies::orderBy('created_at', 'DESC')->get();

        return view('painel.cookies.index', compact('registros'));
    }
}

laravel/app/Http/Controllers/Painel/BonusController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Models\BonusUtilizado;
use App\Models\Bonus;
use App\Models\Cadastros;
use App\Models\User;
use App\Helpers\Tools;

class BonusController extends Controller
{
    public function index()
    {
        $bonus_utilizado = BonusUtilizado::select('*')->orderBy('data', 'desc')->get();
        return view('painel.bonus.index', compact('bonus_utilizado'));
    }

    public function edit(BonusUtilizado $bonus_utilizado, $id)
    {
        $usuario = Cadastros::find($id);
        return view('painel.bonus.edit', compact('usuario'));
    }

    public function update(Request $request, BonusUtilizado $registro, $id)
    {
        try{
            $input = $request->only(['usuario_id', 'valor_bonus', 'numero_nf', 'data']);
            $input['valor'] = $input['valor_bonus'];

            //format date
            $parts = explode('-', $input['data']);
            $date  = $parts[2].'-'.$parts[1].'-'.$parts[0];
            $input['data'] = $date;

            unset($input['valor_bonus']);
            $usuario = $registro->create($input);
            
            //atualiza saldo cliente
            Tools::descontaBonusUtilizado($usuario->usuario_id);
            
            return redirect()->route('painel.bonus.index')->with('sucesso', 'Bônus utilizado adicionado ao usuário.');
        }catch(\Exception $e){
            return back()->withErrors(['Erro ao atualizar bônus utilizado: ' . $e->getMessage()]);
        }
    }

    public function destroy(BonusUtilizado $registro, $id)
    {
        try{
            $registro->find($id)->delete();
            return redirect()->route('painel.bonus.index')->with('sucesso', 'Bônus utilizado deletado.');
        }catch(\Excepion $e){
            return back()->withErrors(['Erro ao deletar nota com bônus utilizado: ' . $e->getMessage()]);
        }
    }
}

laravel/app/Http/Controllers/Painel/CadastrosController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\CadastrosRequest;
use App\Http\Controllers\Controller;
use App\Models\Cadastros;
use App\Models\User;
use Illuminate\Support\Facades\Mail;

class CadastrosController extends Controller
{
    public function index()
    {   
        if(\Auth::user()->tipo == "administracao"){
            $usuarios = Cadastros::all();
        }else{
            $usuarios = Cadastros::where('gerente_automocao_email', '=', \Auth::user()->email)
            ->orWhere('gerente_componentes_email', '=', \Auth::user()->email)
            ->get();                      
        }
        return view('painel.cadastros.index', compact('usuarios'));
    }

    public function create()
    {
        return view('painel.cadastros.create');
    }

    public function store(CadastrosRequest $request, Cadastros $registro){

        try{
            //valida de gerente email está vazio
            if(!$request->has('gerente_automocao_email') && !$request->has('gerente_componentes_email')){
                return back()->withErrors(['Preencha pelo menos um campo Gerente']);
            }

            $input = $request->all();            
            $usuario = $registro->create($input);


            //envia email ao usuario, informando os dados de acesso
            $this->sendMailUserCreated($usuario);

            return redirect()->route('painel.cadastros.index')->with('success', 'Registro criado com sucesso.');
        }catch (\Exception $e) {
            return back()->withErrors(['Erro ao inserir registro: '.$e->getMessage()]);
        }
    }

    public function reenviaEmailUsuario($id)
    {
        $usuario = Cadastros::find($id);
        $this->sendMailUserCreated($usuario);
        return redirect()->route('painel.cadastros.index')->with('success', 'Confirmação de conta reenviada ao usuário.');
    }

    public function edit(Cadastros $registro, $id)
    {
        $usuario = $registro::find($id);
        return view('painel.cadastros.edit', compact('usuario'));
    }

    public function update(CadastrosRequest $request, Cadastros $registro, $id){
        try{
            $registro->find($id)->update($request->all());

            return redirect()->route('painel.cadastros.index')->with('success', 'Registro atualizado com sucesso.');
        }catch(\Exception $e){
            return back()->withErrors(['Erro ao atualizar registro:'. $e->getMessage()]);
        }
    }

    private function sendMailUserCreated($usuario)
    { 
         Mail::send('emails.usuario-criado', ['usuario' => $usuario], function($m) use ($usuario)
         {
             $m->to($usuario->email, config('app.name'))
                ->subject('[ACESSO CRIADO] '.config('app.name'));
         });
    }

    public function destroy(Cadastros $registro, $id)
    {
        $registro->find($id)->delete();
        return redirect()->route('painel.cadastros.index')->with('success', 'Registro deletado com sucesso.');

    }
}

laravel/app/Http/Controllers/Painel/ConfiguracoesController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\ConfiguracoesRequest;
use App\Http\Controllers\Controller;

use App\Models\Configuracoes;

class ConfiguracoesController extends Controller
{
    public function index()
    {
        $registro = Configuracoes::first();

        return view('painel.configuracoes.edit', compact('registro'));
    }

    public function update(ConfiguracoesRequest $request, Configuracoes $registro)
    {
        try {
            $input = $request->all();

            if (isset($input['imagem_de_compartilhamento'])) $input['imagem_de_compartilhamento'] = Configuracoes::upload_imagem_de_compartilhamento();

            $registro->update($input);

            return redirect()->route('painel.configuracoes.index')->with('success', 'Registro alterado com sucesso.');
        } catch (\Exception $e) {
            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);
        }
    }
}

laravel/app/Http/Controllers/Painel/FiltroPesquisaController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Models\Notas;
use App\Models\BonusUtilizado;
use App\Models\BonusTipo;
use App\Helpers\Tools;

class FiltroPesquisaController extends Controller
{
    public function notas(Request $request)
    {
        $pesquisa_registro = Notas::where('numero_nf', '=', $request->get('numero_nf'))
            ->orWhere('razao_social', '=', $request->get('razao_social'))
            ->get() ?: 'Nenhuma nota encontrada.';

        return view($request->get('rota'), compact('pesquisa_registro'));
    }

    public function bonus(Request $request)
    {
        $pesquisa_registro = collect(BonusUtilizado::all())->filter(function($item) use ($request){
            return $item->cadastros->cnpj == $request->get('cnpj');
        });

        return view($request->get('rota'), compact('pesquisa_registro'));
    }

    public function atualizaSaldoBonus($id)
    {
        //atualiza saldo LINHA NOVA
        Tools::recalculaBonus(BonusTipo::LINHA_NOVA, 'total_bonus_linha_nova', $id);
        //atualiza saldo REVENDA
        Tools::recalculaBonus(BonusTipo::REVENDA, 'total_bonus_revenda', $id);
        //atualiza total bonus
        Tools::recalculaTotalBonus($id);
        //recalcula bonus utilizado
        Tools::recalculaBonusUtilizado($id);
        //desconta o total bonus sobre o bonus utilizado
        Tools::descontaBonusUtilizado($id);
        
        return redirect()->route('painel.bonus.index')->with('success', 'Saldo atualizado');
    }
}

laravel/app/Http/Controllers/Painel/GeneratorController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use Illuminate\Support\Facades\Artisan;

class GeneratorController extends Controller
{
    public function index()
    {
        return view('painel.generator.index');
    }

    public function submit(Request $request)
    {
        $this->validate($request, [
            'type'         => 'required',
            'resourceName' => 'required',
            'unitName'     => 'required_if:type,default'
        ]);

        $type = $request->get('type');

        $parameters = [
            'resourceName' => $request->get('resourceName'),
            'fields'       => $request->get('fields'),
        ];

        if(!empty($request->get('campos_nome')[0])) {
            $fields = '';
            foreach ($request->get('campos_nome') as $key => $campo_nome) {
                $field = [
                    $campo_nome,
                    $request->get('campos_tipo')[$key],
                    $request->get('campos_validation')[$key]
                ];

                $field = implode(':', $field);

                if (array_key_exists($key+1, $request->get('campos_nome'))) {
                    $fields .= $field.',';
                } else {
                    $fields .= $field;
                }
            }

            if (!empty($request->get('fields'))) {
                $parameters['fields'] = $request->get('fields').','.$fields;
            } else {
                $parameters['fields'] = $fields;
            }
        }

        if ($type == 'default') {
            $parameters['unitName'] = $request->get('unitName');
            $parameters['--slug']   = $request->get('slug');

            if ($request->get('paginate')) {
                $parameters['--paginate'] = $request->get('paginate');
            }
            if ($request->get('sortable')) {
                $parameters['--sortable'] = true;
            }
            if ($request->get('gallery')) {
                $parameters['--gallery'] = true;
            }
            if ($request->get('categories')) {
                $parameters['--categories'] = true;
            }
            if ($request->get('tags')) {
                $parameters['--tags'] = true;
            }
        }

        if ($request->get('force')) {
            $parameters['--force'] = true;
        }

        try {

            Artisan::call('resource:'.$type, $parameters);
            $output = Artisan::output();

            return back()->with(compact('output'))->withInput();

        } catch (\Exception $e) {

            return back()->withErrors([$e->getMessage()])->withInput();

        }

    }
}

laravel/app/Http/Controllers/Painel/NotasController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Models\Notas;

class NotasController extends Controller
{
    public function index()
    {
        if(\Auth::user()->tipo == "gerente_componentes"){
            $notas = collect(Notas::select('*')->orderBy('created_at', 'desc')->get())->filter(function ($item, $key){
                return $item->cadastros->gerente_componentes_email == \Auth::user()->email;
            });            
        }else if(\Auth::user()->tipo == "gerente_automocao"){
            $notas = collect(Notas::select('*')->orderBy('created_at', 'desc')->get())->filter(function ($item, $key){
                return $item->cadastros->gerente_automocao_email == \Auth::user()->email;
            });
        }else{
            $notas = Notas::select('*')->orderBy('created_at', 'desc')->get();
        }
        return view('painel.notas.index', compact('notas'));
    }

    public function edit($id)
    {
        $nota = Notas::where('id',$id)->first();
        return view('painel.notas.edit', compact('nota'));
    }

    public function update(Request $request, Notas $registro, $id)
    {
        try{
            $input = $request->all();
            $input['status_data'] = date('Y-m-d H:i:s');
            $registro->find($id)->update($input);
            return redirect()->route('painel.notas.index')->with('success', 'Nota atualizada com sucesso.');
        }catch(\Exception $e){
            return back()->withErrors(['Erro ao atualizar nota:' .$e->getMessage()]);
        }
    }

    public function destroy(Notas $registro, $id)
    {
        try{
            $registro->find($id)->delete();
            return redirect()->route('painel.notas.index')->with('success', 'Nota removida com sucesso.');
        }catch(\Exception $e){
            return back()->withErrors(['Erro ao deletar nota: '. $e->getMessage()]);
        }
    }
}

laravel/resources/views/painel/common/filtro-bonus.blade.php
<div class="container-fluid">
    <div class="row">
        <div class="col-12">
            <form action="{{ route('filtro-bonus') }}" method="post">                
                <input type="hidden" name="_token" value="{{ csrf_token() }}">
                <div class="form-group row">
                        <div class="col-lg-3 pl-0">
                            <input type="text" name="cnpj" class="form-control cnpj" value="{{ old('cnpj') }}" placeholder="Cliente/Distribuidor">
                        </div>
                        
                        <input type="hidden" name="rota" value="{!! $rota !!}">
                <div class="col-lg-2 ">
                    <input type="submit" value="Pesquisar" class="btn btn-info">
                </div>
                </div>
            </form>
        </div>
    </div>
</div>

laravel/resources/views/painel/common/filtro-nota.blade.php
<div class="container-fluid">
    <div class="row">
        <div class="col-12">
            <form action="{{ route('filtro-notas') }}" method="post">                
                <input type="hidden" name="_token" value="{{ csrf_token() }}">
                <div class="form-group row">
                        <div class="col-lg-3 pl-0">                        
                            <input type="number" name="numero_nf" class="form-control" value="{{ old('numero_nf') }}" placeholder="Nº Nota Fiscal">
                        </div>
                        <div class="col-lg-3 p-0 ">
                            <input type="text" name="razao_social" class="form-control" value="{{ old('razao_social') }}" placeholder="Razão Social">
                        </div>
                        <input type="hidden" name="rota" value="{!! $rota !!}">
                <div class="col-lg-2 ">
                    <input type="submit" value="Pesquisar" class="btn btn-info">
                </div>
                </div>
            </form>
        </div>
    </div>
</div>

laravel/resources/views/painel/common/flash.blade.php
@if(session('success'))
   <div class="alert alert-block alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {!! session('success') !!}
    </div>
@endif

@if($errors->any())
    <div class="alert alert-block alert-danger">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        @foreach($errors->all() as $error)
        {!! $error !!}<br>
        @endforeach
    </div>
@endif

laravel/resources/views/painel/common/header.blade.php
<nav class="navbar navbar-default navbar-static-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{{ url('/') }}">{{ config('app.name') }}</a>
        </div>

        <div id="navbar" class="navbar-collapse collapse">
            @include('painel.common.nav')

            <ul class="nav navbar-nav navbar-right">
                <li class="dropdown @if(Tools::routeIs(['painel.usuarios*', 'painel.configuracoes*', 'painel.politica-de-privacidade*', 'painel.aceite-de-cookies*'])) active @endif">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <span class="glyphicon glyphicon-cog small" style="margin-right:3px"></span>
                        <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                        @if (Auth::user()->tipo == "administracao")                            
                            <li @if(Tools::routeIs('painel.politica-de-privacidade*')) class="active" @endif>
                                <a href="{{ route('painel.politica-de-privacidade.index') }}">Politica de Privacidade</a>
                            </li>
                            <li @if(Tools::routeIs('painel.aceite-de-cookies*')) class="active" @endif>
                                <a href="{{ route('painel.aceite-de-cookies') }}">Aceite de Cookies</a>
                            </li>
                            <li @if(Tools::routeIs('painel.configuracoes*')) class="active" @endif>
                                <a href="{{ route('painel.configuracoes.index') }}">Configurações</a>
                            </li>
                            <li @if(Tools::routeIs('painel.usuarios*')) class="active" @endif>
                                <a href="{{ route('painel.usuarios.index') }}">Usuários</a>
                            </li>
                        @endif
                        <li><a href="{{ route('logout') }}">Logout</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>

laravel/resources/views/painel/common/nav.blade.php
<ul class="nav navbar-nav">
    <li class="dropdown @if(Tools::routeIs('painel.cadastros*')) active @endif">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Clientes
            <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
            <li @if(Tools::routeIs('painel.cadastros.index')) class="active" @endif>
                <a href="{{ route('painel.cadastros.index') }}">Listar</a>
            </li>
        </ul>
    </li>

    <li class="dropdown @if(Tools::routeIs('painel.notas*')) active @endif">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Notas
            <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
            <li @if(Tools::routeIs('painel.notas.index')) class="active" @endif>
                <a href="{{ route('painel.notas.index') }}">Listar</a>
            </li>
        </ul>
    </li>

    @if (\Auth::user()->tipo == "administracao")  
        <li class="dropdown @if(Tools::routeIs('painel.bonus*')) active @endif">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Bônus utilizado
                <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
                <li @if(Tools::routeIs('painel.bonus.index')) class="active" @endif>
                    <a href="{{ route('painel.bonus.index') }}">Clientes</a>
                </li>
            </ul>
        </li>
    @endif

    <!--<li @if(Tools::routeIs('painel.notas*')) class="active" @endif>
        <a href="#">Notas</a>
    </li>-->
</ul>

laravel/resources/views/painel/common/template.blade.php
<!doctype html>
<html lang="pt-BR">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <base href="{{ url('/') }}">

    <title>{{ config('app.name') }} - Painel Administrativo</title>

    <link rel="stylesheet" href="{{ asset('assets/vendor/bootswatch-dist/css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/vendor/jquery-ui/themes/cupertino/jquery-ui.min.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/css/vendor.painel.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/css/painel.css') }}">
</head>
<body>
    @include('painel.common.header')

    <div class="container" style="padding-bottom:30px;">
        @yield('content')
    </div>

    <script src="//ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
	<script>window.jQuery || document.write('<script src="{{ asset('assets/vendor/jquery/dist/jquery.min.js') }}"><\/script>')</script>
    <script src="{{ asset('assets/vendor/ckeditor/ckeditor.js') }}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.11.2/jquery.mask.min.js" integrity="sha512-Y/GIYsd+LaQm6bGysIClyez2HGCIN1yrs94wUrHoRAD5RSURkqqVQEU6mM51O90hqS80ABFTGtiDpSXd2O05nw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="{{ asset('assets/js/vendor.painel.js') }}"></script>
    <script src="{{ asset('assets/js/painel.js') }}"></script>


@yield('script')
</body>
</html>